package com.example.persona.enums;

import lombok.Getter;

@Getter
public enum ErrorCode {
    VALIDATION_ERROR("VAL-001"),
    RESOURCE_NOT_FOUND("RSC-001"),
    BUSINESS_ERROR("BUS-001"),
    UNAUTHORIZED("SEC-001"),
    FORBIDDEN("SEC-002"),
    CACHE_ERROR("CHE-ERR"),
    INTERNAL_SERVER_ERROR("SYS-001"),
    TRANSLATION_NOT_FOUND("TRA-NOT-FOUND"),
    TRANSLATION_ALREADY_EXISTS("TRA-ALREADY-EXISTS"),
    SCHEDULE_NOT_FOUND("SCH-NOT-FOUND"),
    SCHEDULE_AMOUNT_EXCEEDS_MAXIMUM_LIMIT("SCH-AMT-EXCEEDS-MAX"),
    SCHEDULE_AMOUNT_BELOW_MINIMUM_LIMIT("SCH-AMT-BELOW-MIN"),
    SCHEDULE_MAX_COUNT_REACHED("SCH-MAX-COUNT-REACHED"),
    SCHEDULE_NOT_PAUSED("SCH-NOT-PAUSED"),
    EVENT_UPDATE_NOT_FOUND("EVE-NOT-FOUND"),
    INVALID_SCHEDULE_STATE("SCH-INVALID-STATE"),
    DATABASE_INSERT_ERROR("DB-INSERT-ERROR"),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED"),
    ERR_AUTH_INVALID("ERR_AINV");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }
}
