package com.example.persona.pinless.model.dto;

import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import lombok.Data;

@Data
public class AuthResolveRequest {

    @NotBlank(message = "customerNo is required")
    @Size(max = 50, message = "customerNo must not exceed 50 characters")
    private String customerNo;

    @NotBlank(message = "accountId is required")
    @Size(max = 64, message = "accountId must not exceed 64 characters")
    private String accountId;

    @NotNull(message = "amount is required")
    @DecimalMin(value = "0.01", message = "amount must be greater than 0")
    @DecimalMax(value = "99999999999999.99", message = "amount exceeds maximum allowed value")
    @Digits(integer = 14, fraction = 2, message = "amount must have at most 2 decimal places")
    private BigDecimal amount;

    @Pattern(regexp = "[A-Z]{3}", message = "currency must be a 3-letter ISO code (e.g. USD, KHR)")
    private String currency; // default: USD

    @Pattern(regexp = "MOBAPP|WEB|POS", message = "channel must be one of: MOBAPP, WEB, POS")
    private String channel; // default: MOBAPP

    @Size(max = 50, message = "txnType must not exceed 50 characters")
    private String txnType;

    /**
     * Optional idempotency key from mobile.
     * If provided and a response was already produced for this key,
     * the cached response is returned without re-processing.
     * Recommended format: UUID generated by mobile per resolve attempt.
     * TTL: 60 seconds — covers mobile retry window.
     */
    @Size(max = 64, message = "idempotencyKey must not exceed 64 characters")
    private String idempotencyKey;
}
