-- V8: Location categories & tags (FR-03)
-- Managed, multilingual, icon-bearing categories that back GET /categories/list
-- and the locator filters. Categories are referenced by Locations via their `code`.
--
-- Column names mirror the JPA entities (BaseModel + MultilingualContent embeddable)
-- so Hibernate ddl validation/update does not fight these definitions.

-- ── Tags ──────────────────────────────────────────────────────────────────────
CREATE TABLE dgtl_location_tag (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(100)  NOT NULL,
    name_en       VARCHAR(255),
    name_km       VARCHAR(255),
    name_zh       VARCHAR(255),
    -- BaseModel auditing columns
    created_by    VARCHAR(255),
    created_date  TIMESTAMP,
    modified_by   VARCHAR(255),
    modified_date TIMESTAMP,
    status        VARCHAR(255),
    version       INTEGER,
    CONSTRAINT uk_location_tag_code UNIQUE (code)
);

-- ── Categories ──────────────────────────────────────────────────────────────
CREATE TABLE dgtl_location_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(100)  NOT NULL,
    name_en         VARCHAR(255),
    name_km         VARCHAR(255),
    name_zh         VARCHAR(255),
    description_en  VARCHAR(255),
    description_km  VARCHAR(255),
    description_zh  VARCHAR(255),
    mark_icon       VARCHAR(255),
    mark_icon_url   VARCHAR(1000),
    display_order   INTEGER       NOT NULL DEFAULT 0,
    -- BaseModel auditing columns
    created_by      VARCHAR(255),
    created_date    TIMESTAMP,
    modified_by     VARCHAR(255),
    modified_date   TIMESTAMP,
    status          VARCHAR(255),
    version         INTEGER,
    CONSTRAINT uk_location_category_code UNIQUE (code)
);

-- ── Category ↔ Tag join ───────────────────────────────────────────────────────
CREATE TABLE dgtl_location_category_tag (
    category_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL,
    PRIMARY KEY (category_id, tag_id),
    CONSTRAINT fk_loc_cat_tag_category FOREIGN KEY (category_id) REFERENCES dgtl_location_category (id) ON DELETE CASCADE,
    CONSTRAINT fk_loc_cat_tag_tag      FOREIGN KEY (tag_id)      REFERENCES dgtl_location_tag (id)      ON DELETE CASCADE
);

CREATE INDEX idx_location_category_display_order ON dgtl_location_category (display_order);

-- ── Seed: the four base categories (bridges the LocationType enum) ─────────────
INSERT INTO dgtl_location_category
    (code, name_en, name_km, display_order, status, version)
VALUES
    ('branch',       'Bank Branch',       'សាខាធនាគារ',          1, 'ACTIVE', 0),
    ('atm_crm',      'ATM/CRM',           'ម៉ាស៊ីន ATM/CRM',      2, 'ACTIVE', 0),
    ('master_agent', 'Bank Master Agent', 'ភ្នាក់ងារមេ',          3, 'ACTIVE', 0),
    ('agent',        'Bank Agent',        'ភ្នាក់ងារ',            4, 'ACTIVE', 0);

COMMENT ON TABLE dgtl_location_category     IS 'Location categories (FR-03) used by locator filters; referenced by locations via code.';
COMMENT ON TABLE dgtl_location_tag          IS 'Tags attachable to location categories (FR-03).';
COMMENT ON TABLE dgtl_location_category_tag IS 'Many-to-many join between location categories and tags.';
